services:
  estructura:
    image: gestion_academica
    restart: always
    networks:
      mired:
        aliases:
          - academica.universidad.localhost
    environment:
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

    env_file:
      - .env

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.academica-service.rule=Host(`academica.universidad.localhost`)"
      - "traefik.http.routers.academica-service.entrypoints=websecure"
      - "traefik.http.routers.academica-service.tls=true"
      - "traefik.http.services.academica-service.loadbalancer.server.port=5000"

      # Middlewares por separado
      - "traefik.http.middlewares.acad-cb.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.acad-cb.circuitbreaker.expression=ResponseCodeRatio(500,600,0,600) > 0.25"
      - "traefik.http.middlewares.acad-cb.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

      - "traefik.http.middlewares.acad-retry.retry.attempts=4"
      - "traefik.http.middlewares.acad-retry.retry.initialinterval=100ms"

      # Asignar los middlewares al router
      - "traefik.http.routers.academica-service.middlewares=acad-cb,acad-retry"

      - "traefik.docker.network=mired"
networks:
  mired:
    external: true
