services:
  estructura:
    image: gestion_academica
    #deploy:
    #  replicas: 5
    container_name: app_gestion
    restart: always
    networks:
      - mired
    ports:
    - "5000:5000"
    environment:
      - FLASK_CONTEXT=production
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HASHIDS_MIN_LENGTH=${HASHIDS_MIN_LENGTH}
      - HASHIDS_ALPHABET=${HASHIDS_ALPHABET}
      - HASHIDS_SALT=${HASHIDS_SALT}
      - SECRET_KEY=${SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.universidad.localhost`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.docker.network=mired"
      #- "traefik.http.routers.backend.entrypoints=websecure"
      # Retry middleware
      #- "traefik.http.middlewares.backend-retry.retry.attempts=3"
      #- "traefik.http.middlewares.backend-retry.retry.initialinterval=100ms"
      #- "traefik.http.routers.backend.middlewares=backend-retry"

networks:
  mired:
    external: true
